CREATE DATABASE Contractor_Segmentation;
USE Contractor_Segmentation;

CREATE TABLE data_analysis (
    Slno INT PRIMARY KEY,
    Contractor_name VARCHAR(50),
    Last_Project_Price INT,
    Cost_management DECIMAL(10, 2),
    Safety_record DECIMAL(10, 2),
    Experience INT,
    Technical_experience VARCHAR(50),
    Labour_Availability VARCHAR(50),
    Material_Availability VARCHAR(50),
    Equipment_Availability VARCHAR(50),
    Financial_Stability DECIMAL(10, 2),
    Bonding_Capacity DECIMAL(10, 2),
    Feedback DECIMAL(10, 2),
    Testimonials VARCHAR(50),
    Permit_And_Licensing VARCHAR(50),
    Resource_Allocation VARCHAR(50),
    Adaptability_AND_Flexibility VARCHAR(50),
    Regional_language CHAR(3),
    English_Language CHAR(3),
    Critical_Thinking DECIMAL(12, 2),
    Required_Response_Time CHAR(3),
    Service_Quality DECIMAL(12,2),
    Timely_Delivered CHAR(3),
    Certification_A CHAR(3),
    Training_Upto_Date CHAR(3),
    Carbon_Footprint CHAR(3),
    Energy_Efficiency CHAR(3),
    Recycling_Program CHAR(3),
    Quality_of_Work DECIMAL(12, 2),
    Client_Satisfaction DECIMAL(10, 2),
    Standing_In_Industry VARCHAR(50),
    Insurance_Coverage CHAR(3),
    Document_Control CHAR(3),
    Regional_Experience DECIMAL(12, 2),
    Supply_Chain VARCHAR(50)
);

INSERT INTO data_analysis (
    Slno, Contractor_name, Last_Project_Price, Cost_management, Safety_record, Experience, Technical_experience, 
    Labour_Availability, Material_Availability, Equipment_Availability, Financial_Stability, Bonding_Capacity, Feedback, 
    Testimonials, Permit_And_Licensing, Resource_Allocation, Adaptability_AND_Flexibility, Regional_language, English_Language, 
    Critical_Thinking, Required_Response_Time, Service_Quality, Timely_Delivered, Certification_A, Training_Upto_Date, 
    Carbon_Footprint, Energy_Efficiency, Recycling_Program, Quality_of_Work, Client_Satisfaction, Standing_In_Industry, 
    Insurance_Coverage, Document_Control, Regional_Experience, Supply_Chain
)
VALUES
(1, "Crescent Contractors", 10, 0.95, 0.90, 10, "No", "Yes", "Yes", "Yes", 9.2, 8.8, "4.2", "Average", "Yes", "Yes", "Yes", "Yes", "Yes", 9.2, "Yes", 9.8, "Yes", "Yes", "Yes", "Yes", "Yes", "Yes", 8.5, 7.9, "Yes", "Yes", "Yes", 9.4, "No"),
(2, "Bright Builders Inc.", 25, 0.93, 0.91, 16, "Yes", "Yes", "Yes", "Yes", 9.4, 9.4, "4.7", "Good", "Yes", "Yes", "Yes", "Yes", "Yes", 9.4, "Yes", 8.2, "Yes", "Yes", "Yes", "Yes", "Yes", "Yes", 9.4, 9.6, "Yes", "Yes", "Yes", 9.1, "Yes"),
(3, "Elite Engineering Solutions", 8, 0.96, 0.88, 8, "No", "Yes", "Yes", "Yes", 8.5, 8.9, "4.1", "Average", "Yes", "Yes","No", "Yes", "Yes", 7.2, "No", 8.4, "No", "Yes", "Yes", "No", "No", "No", 8.4, 8.3, "No", "Yes","No", 5.5, "No"),
(4, "Dynamic Developments", 15, 0.91, 0.89, 15, "Yes", "Yes", "Yes", "Yes", 8.9, 8.4, "4.5", "Good", "Yes", "Yes", "Yes", "Yes", "Yes", 9.4, "Yes", 9.3, "Yes", "Yes", "Yes", "Yes", "Yes", "Yes", 9.7, 9.3, "Yes", "Yes", "Yes", 9.5, "Yes"),
(5, "Frontier Construction Co.", 9, 0.85, 0.89, 5, "No", "Yes", "Yes", "No", 8.4, 8.5, "4.1", "Average", "Yes", "Yes", "Yes", "Yes", "Yes", 9.6, "Yes", 9.5, "Yes", "Yes", "Yes", "Yes", "No", "No", 8.3, 8.2, "No", "Yes", "Yes", 9.7, "No"),
(6, "Global Builders & Developers", 20, 0.96, 0.92, 20, "Yes", "Yes", "Yes", "Yes", 9.6, 9.4, "4.8", "Good", "Yes", "Yes", "Yes", "Yes", "Yes", 9.8, "Yes", 9.6, "Yes", "Yes", "Yes", "Yes", "Yes", "Yes", 9.5, 9.2, "Yes", "Yes", "Yes", 8.8, "Yes"),
(7, "Horizon Construction Services", 10, 0.96, 0.93, 14, "Yes", "Yes", "Yes", "Yes", 9.7, 8.8, "4.1", "Average", "Yes", "Yes", "Yes", "Yes", "Yes", 9.5, "Yes", 9.1, "Yes", "Yes", "Yes", "Yes", "Yes", "Yes", 8.6, 8.1, "Yes", "Yes", "Yes", 9.3, "No"),
(8, "Innovative Construction Ltd.", 5, 0.85, 0.88, 8, "No", "Yes", "Yes", "Yes", 9.1, 9.2, "4.1", "Average", "Yes", "Yes", "No", "Yes", "Yes", 7.4, "No", 7.8, "No", "Yes", "Yes", "No", "No", "No", 8.4, 8.4, "No", "Yes", "No", 4.5, "No"), 
(9, "Jaguar Construction", 24, 0.98, 0.96, 14, "Yes", "Yes", "Yes", "Yes", 9.9, 9.4, "4.9", "Good", "Yes", "Yes", "Yes", "Yes", "Yes", 8.2, "Yes", 9.5, "Yes", "Yes", "Yes", "Yes", "Yes", "Yes", 9.2, 9.1, "Yes", "Yes", "Yes", 8.5, "Yes"),
(10, "Kinetic Construction Corp.", 12, 0.95, 0.88, 3, "No", "Yes", "Yes", "No", 9.3, 8.2, "4.1", "Average", "Yes", "Yes", "Yes", "Yes", "Yes", 8.9, "Yes", 9.2, "Yes", "Yes", "Yes", "Yes", "Yes", "Yes", 8.2, 8.2, "No", "Yes", "Yes", 8.7, "No"),
(11, "Lighthouse Builders", 3, 0.89, 0.85, 9, "No", "Yes", "Yes", "Yes", 9.1, 8.9, "4.2", "Average", "Yes", "Yes", "No", "Yes", "Yes", 9.7, "No", 8.4, "No", "Yes", "Yes", "No", "No", "No", 8.3, 8.4, "No", "Yes", "No", 4.2, "No"),
(12, "Nexus Contracting Services", 25, 0.96, 0.94, 15, "Yes", "Yes", "Yes", "Yes", 8.2, 8.5, "4.6", "Good", "Yes", "Yes", "Yes", "Yes", "Yes", 8.8, "Yes", 9.8, "Yes", "Yes", "Yes", "Yes", "Yes", "Yes", 9.7, 9.6, "Yes", "Yes", "Yes", 8.9, "Yes"),
(13, "Omega Builders Group", 8, 0.98, 0.90, 12, "Yes", "Yes", "Yes", "Yes", 8.7, 8.9, "3.9", "Average", "Yes", "Yes", "Yes", "Yes", "Yes", 8.4, "Yes", 8.5, "Yes", "Yes", "Yes", "Yes", "No", "Yes", 7.9, 7.8, "Yes", "Yes", "Yes", 8.6, "No"),
(14, "Pioneer Construction Ltd.", 80, 0.96, 0.90, 18, "Yes", "Yes", "Yes", "No", 8.9, 9.8, "4.9", "Good", "Yes", "Yes", "Yes", "Yes", "Yes", 8.1, "Yes", 9.3, "Yes", "Yes", "Yes", "Yes", "Yes", "Yes", 9.6, 9.6, "Yes", "Yes", "Yes", 8.8, "Yes" ),
(15, "Quantum Contractors", 14, 0.95, 0.90, 13, "Yes", "Yes", "Yes", "Yes", 8.2, 8.7, "4.2", "Average", "Yes", "Yes", "Yes", "Yes", "Yes", 8.5, "Yes", 8.3, "Yes", "Yes", "Yes", "Yes", "Yes", "Yes", 8.5, 8.4, "Yes", "Yes", "Yes", 8.9, "No"),
(16, "Renaissance Construction Inc.", 15, 0.98, 0.90, 11, "Yes", "Yes", "Yes", "Yes", 9.3, 8.8, "4.3", "Good", "Yes", "Yes", "Yes", "Yes", "Yes", 8.3, "Yes", 8.4, "Yes", "Yes", "Yes", "Yes", "Yes", "Yes", 8.4, 8.5, "Yes", "Yes", "Yes", 8.7, "No"),
(17, "Skyline Construction Co.", 9, 0.99, 0.90, 22, "Yes", "Yes", "Yes", "Yes", 9.7, 9.7, "4.5", "Good", "Yes", "Yes", "Yes", "Yes", "Yes", 8.1, "Yes", 9.7, "Yes", "Yes", "Yes", "Yes", "No", "Yes", 9.6, 9.3, "Yes", "Yes", "Yes", 9.8, "Yes"),
(18, "Titan Builders", 27, 0.98, 0.90, 17, "Yes", "Yes", "Yes", "Yes", 9.9, 9.8, "4.8", "Good", "Yes", "Yes", "Yes", "Yes", "Yes", 7.3, "Yes", 8.1, "Yes", "Yes", "Yes", "Yes", "Yes", "Yes", 9.1, 9.1, "Yes", "Yes", "Yes", 9.9, "Yes"),
(19, "Vertex Construction & Design", 5, 0.94, 0.90, 7, "No", "Yes", "Yes", "Yes", 7.9, 7.4, "4.2", "Average", "Yes", "Yes", "No", "Yes", "Yes", 9.6, "No", 7.9, "No", "Yes", "Yes", "No", "No", "No", 8.5, 8.3, "No", "Yes", "No", 6.2, "Yes"),
(20, "Western Builders Group", 16, 0.97, 0.90, 8, "No", "Yes", "Yes", "No", 9.2, 9.6, "4.1", "Average", "Yes", "Yes", "Yes", "Yes", "Yes", 8.3, "Yes", 8.8, "Yes", "Yes", "Yes", "Yes", "Yes", "Yes", 8.3, 8.1, "No", "Yes", "Yes", 8.8, "Yes"),
(21, "Xcel Construction", 45, 0.89, 0.90, 12, "Yes", "Yes", "Yes", "Yes", 8.9, 9.2, "4.7", "Good", "Yes", "Yes", "Yes", "Yes", "Yes", 8.1, "Yes", 9.4, "Yes", "Yes", "Yes", "Yes", "Yes", "Yes", 9.6, 8.7, "Yes", "Yes", "Yes", 9.7, "Yes"),
(22, "Zenith Contractors Inc.", 2, 0.92, 0.90, 6, "No", "Yes", "Yes", "Yes", 9.2, 8.7, "4.1", "Average", "Yes", "Yes", "No", "Yes", "Yes", 9.8, "No", 8.2, "No", "Yes", "Yes", "No", "No", "No", 8.1, 8.3, "No", "Yes", "No", 7.7, "No"),
(23, "Apex Construction Group", 30, 0.94, 0.90, 15, "Yes", "Yes", "Yes", "No", 9.9, 9.9, "4.8", "Good", "Yes", "Yes", "Yes", "Yes", "Yes", 7.5, "Yes", 9.5, "Yes", "Yes", "Yes", "Yes", "Yes", "Yes", 9.7, 9.3, "Yes", "Yes", "Yes", 9.5, "Yes"),
(24, "Alpha Construction Solutions", 13, 0.95, 0.90, 18, "Yes", "Yes", "Yes", "No", 9.2, 9.8, "4.2", "Average", "Yes", "Yes", "Yes", "Yes", "Yes", 7.9, "Yes", 8.3, "Yes", "Yes", "Yes", "Yes", "Yes", "Yes", 8.4, 8.4, "Yes", "Yes", "Yes", 8.3, "No"),
(25, "Echo Engineering and Construction", 9, 0.92, 0.90, 16, "No", "Yes", "Yes", "Yes", 8.9, 9.1, "4.3", "Good", "Yes", "Yes", "Yes", "Yes", "Yes", 7.2, "Yes", 7.9, "Yes", "Yes", "Yes", "Yes", "No", "Yes", 8.3, 8.5, "Yes", "Yes", "Yes", 8.1, "No");

SELECT * FROM data_analysis;
